version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/app"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/lib"
    schedule:
      interval: "weekly"
